ws_port: 9360 # default port for puffer
portal_settings:
  secret_key: PUFFER_PORTAL_SECRET_KEY # change to puffer export password
  debug: true
  allowed_hosts:
    - '*'
postgres_connection:
  host: 127.0.0.1
  port: 5432 # change to the port setup for the DB, default is 5432
  dbname: puffer1 # change to DB name
  user: puffer1 # change to DB username
  password: PUFFER_PORTAL_DB_KEY # change to DB export password
enable_logging: true
log_dir: /home/ubuntu/puffer/src/monitoring # change to your own logging dir
influxdb_connection:
  host: 127.0.0.1
  port: 8086 # change to the port setup for the DB, default is 8086
  dbname: puffer1 # change to DB name
  user: puffer1 # change to DB username
  password: INFLUXDB_PASSWORD # change to DB export password
enforce_moving_live_edge: false
media_dir: /home/ubuntu/puffer/media-181230 # change to your own media dir
channels:
  - nbc
channel_configs:
  abc:
    live: true
    video:
      1280x720: [20, 22, 24, 26]
      854x480: [22, 24, 26]
      640x360: [24, 26]
      426x240: [26]
    audio:
      - 128k
      - 64k
      - 32k
    present_delay_chunk: 300
  nbc:
    live: true
    video:
      1920x1080: [22, 24]
      1280x720: [20, 22, 24, 26]
      854x480: [24, 26]
      640x360: [24]
      426x240: [26]
    audio:
      - 128k
      - 64k
      - 32k
    present_delay_chunk: 300
  fox:
    live: true
    video:
      1280x720: [20, 22, 24, 26]
      854x480: [22, 24, 26]
      640x360: [24, 26]
      426x240: [26]
    audio:
      - 128k
      - 64k
      - 32k
    present_delay_chunk: 300
  pbs:
    live: true
    video:
      1920x1080: [22, 24]
      1280x720: [20, 22, 24, 26]
      854x480: [24, 26]
      640x360: [24]
      426x240: [26]
    audio:
      - 128k
      - 64k
      - 32k
    present_delay_chunk: 300
  cbs:
    live: true
    video:
      1920x1080: [22, 24]
      1280x720: [20, 22, 24, 26]
      854x480: [24, 26]
      640x360: [24]
      426x240: [26]
    audio:
      - 128k
      - 64k
      - 32k
    present_delay_chunk: 300
  univision:
    live: true
    video:
      1280x720: [20, 22, 24, 26]
      854x480: [22, 24, 26]
      640x360: [24, 26]
      426x240: [26]
    audio:
      - 128k
      - 64k
      - 32k
    present_delay_chunk: 300
# experiments:
  # - num_servers: 1
  #   fingerprint:
  #     abr: pensieve
  #     cc: cubic
  #     abr_config:
  #       pensieve_path: "/home/puffer/third_party/pensieve/multi_video_sim/rl_test.py"
  #       nn_path: "/home/puffer/models/pensieve/nn_model_ep_77400.ckpt"
  # - num_servers: 1
  #   fingerprint:
  #     abr: mpc
  #     abr_config:
  #       rebuffer_length_coeff: 100
  #     cc: cubic
  # - num_servers: 1
  #   fingerprint:
  #     abr: robust_mpc
  #     abr_config:
  #       rebuffer_length_coeff: 100
  #     cc: cubic
  # - num_servers: 1
  #   fingerprint:
  #     abr: linear_bba
  #     abr_config:
  #       upper_reservoir: 0.9
  #     cc: cubic
  #  - num_servers: 1
  #    fingerprint:
  #      abr: pensieve
  #      cc: bbr
  #      abr_config:
  #        pensieve_path: "/home/ubuntu/puffer/third_party/pensieve/multi_video_sim/rl_test.py"
  #        nn_path: "/home/ubuntu/puffer/models/pensieve/nn_model_ep_77400.ckpt"


  # - num_servers: 1
  #   fingerprint:
  #     abr: linear_bba
  #     cc: cubic 
  #     abr_config:
  #       upper_reservoir: 0.9
  #     cc_config:
  #       cc_monitoring_path: "/home/ubuntu/cc_monitoring/cc_"
  #       random_cc: false
  #       cc_scoring_path: "/home/ubuntu/cc_scoring/cc_score_"
  #       scoring_type: "ssim"
  #       scoring_mu: 1.0
  #       scoring_lambda: 1.0
        # model_path: "/home/ubuntu/cc_monitoring/other"
        # history_size: 5
        # sample_size: 40
  # - num_servers: 4
  #   fingerprint:
  #     abr: robust_mpc
  #     cc: bbr
  # - num_servers: 4
  #   fingerprint:
  #     abr: mpc
  #     abr_config:
  #       rebuffer_length_coeff: 100
  #     cc: bbr


  # - num_servers: 1
  #   fingerprint:
  #    abr: puffer_exp3
  #    version: demo
  #    abr_config:
  #      model_dir: ./weights/ttp/original
  #      exp3_dir: ./weights/exp3/
  #      rebuffer_length_coeff: 100
  #      max_lookahead_horizon: 1
  #      normalization_dir: ./weights/kmeans/
  #      use_puffer: false
  #      training_mode: true
  #      learning_rate: 0.001
  #      delta: 0.7
  #      clusters: 3
  #    cc: bbr
     
  # - num_servers: 1
  #   fingerprint:
  #    abr: puffer_ttp
  #    abr_config:
  #      model_dir: ./weights/ttp/original
  #      rebuffer_length_coeff: 100
  #      collect_data: true
  #      hidden2_model_dir: ./weights/ttp/hidden2/
  #      max_lookahead_horizon: 1
  #    cc: bbr

  # - num_servers: 1
  #   fingerprint:
  #     abr: puffer_reinforce
  #     abr_name: puffer_reinforce_train
  #     abr_config:
  #       model_dir: ./weights/ttp/hidden2/
  #       policy_model_dir: ./weights/policy/cpp/
  #       rebuffer_length_coeff: 100
  #       max_lookahead_horizon: 1
  #       training_mode: true
  #     cc: bbr
