all_models:
  - model_name: "random"

  - model_name: "idModel"

  - model_name: "constant_0"
    cc_id: 0

  - model_name: "constant_1"
    cc_id: 1

  - model_name: "constant_2"
    cc_id: 2

  - model_name: "resettingExp3"
    should_clear_weights: true
    exp3_save_name: '' # '' means default
    should_load_exp3: false # should load exp3

  - model_name: "exp3"
    should_clear_weights: false
    exp3_save_name: '' # '' means default
    should_load_exp3: true # should load exp3

  - model_name: "sl"
    sl_output_type: "ssim"
    save_name: '' # '' means default
    sl_model_name: '' # '' means default

  - model_name: "clusterModel"
    context_layers: []
    num_clusters: 0
    cluster_name: '' # '' means default
    cluster_contextless: false # uses the sl model

  - model_name: "exp3Kmeans"
    save_name: '' # '' means default

  - model_name: "exp3KmeansAutoEncoder"
    save_name: '' # '' means default
    cluster_type: 'ae'


  - model_name: "contextlessExp3Kmeans"
    save_name: '' # '' means default

    # cluster diferent setting
    cluster_contextless: true # don't use the sl model for context

  - model_name: "stackingModel"
    models: ["constant_0", "constant_1", "constant_2", "resettingExp3", "exp3Kmeans", "sl", "contextlessExp3Kmeans"]

  - model_name: "ae"
    ae_sizes: []
    ae_model_name: ""

  - model_name: "rl"
    rl_model_name: rl_weights_abr_linear_bba_v1.0_ssim.pt
    rl_weights_path: '/home/mike/puffer/cc_cpp_weights/'
    rl_gamma: 0.999

  - model_name: 'srl'
    srl_model_name: srl_weights_abr_linear_bba_v1.0_ssim.pt
    srl_weights_path: '/home/mike/puffer/cc_cpp_weights/'
    context_type: 'sl' # options are ['contextless', 'sl', 'ae']
    srl_gamma: 0.999
  

servers:
  server_port: 5675
  model_name: 'contextlessExp3Kmeans'
  test_models: ["constant_0", "constant_1", "constant_2", "resettingExp3", "exp3Kmeans", "sl", "contextlessExp3Kmeans"]

paths:
  cc_monitoring_path: "/home/mike/cc_monitoring/cc_" # start path to save the logging file of the cc data
  cc_scoring_path: "/home/mike/cc_scoring/cc_score_" # start path to save the scoring file of the abr data


contexts:
  sl_model_name: sl_weights_4_abr_linear_bba_v1.0_ssim.pt # the model to generate context from
  # [500, 200, 100, 80, 50, 40, 30, 20] = layers
  context_layers: [7] # the layers of the model to generate context from


clusters:
# new for clusters
  num_clusters: 40
  saving_cluster_path: '/home/mike/puffer/clusters/'
  remove_bad_files: false #remove files without internet problems in the training of the cluster
  sl_output_type: 'ssim'
  cluster_type: 'sl'

exp3:
  exp3_explore_parameter: 0.1
  exp3_model_path: '/home/mike/puffer/exp3/'


nn_model:
  epochs: 5
  model_network_sizes: [500, 200, 100, 80, 50, 40, 30, 20]
  batch_size: 16
  lr: 1e-4
  betas: (0.5, 0.999)
  version: 1.0
  weights_decay: 1e-4
  weights_path: '/home/mike/puffer/cc_weights/' # start path to the place where to store the nn weights for python
  cpp_weights_path: '/home/mike/puffer/cc_cpp_weights/' # start path to the place where to store the nn weights for cpp


ae_model:
  ae_model_name: ae_weights_4_abr_linear_bba_v1.0_ssim.pt
  ae_sizes: [500, 200, 100, 80, 50, 40, 30, 20]
  ae_weights_path: "/home/mike/puffer/cc_weights/"

rl_training_settings:
  rl_rounds_to_save: 1
  rl_sleep_sec: 1
  rl_batch_size: 3
  rl_min_measuremets: 10
  rl_logs_file: './weights/policy/reinforce_server_logs.txt'

rl_model:
  rl_model_name: rl_weights_abr_linear_bba_v1.0_ssim.pt
  rl_weights_path: '/home/mike/puffer/cc_cpp_weights/'
  rl_gamma: 0.999

srl_model:
  srl_model_name: srl_weights_abr_linear_bba_v1.0_ssim.pt
  srl_weights_path: '/home/mike/puffer/cc_cpp_weights/'
  context_type: 'sl' # options are ['contextless', 'sl', 'ae']
  srl_gamma: 0.999


fingerprint:
  cc_config:
    # function: q(Ci) - lambda * abs(q(Ci) - q(Ci-1)) - mu * rebuffer_time_i, supported scorings: ssim, bit_rate
    # scoring params

    # scoring_type: "bit_rate"
    # scoring_mu: 4.3
    # scoring_lambda: 1.0
    scoring_function_type: "ssim" # the scoring method
    buffer_length_coef: 100.0
    quality_change_qoef: 1.0

    #state params
    history_size: 8 # how much previous chunks does the nn remember
    random_sample_size: 100 # how much from previous chunks it gets as input
    abr_time: true # replace cc each abr or once every _ time
    nn_roundup: 500 # control the rate of change cc in case abr_time is false

    random_cc: false # should replace the cc during runtime, ignored in the code

  ccs: ["bbr", "vegas", "cubic"] # all ccs
  cc: bbr # starting cc

  #ABRS
  abr: linear_bba
  abr_config:
    upper_reservoir: 0.9

  # abr: pensieve
  # abr_config:
  #   pensieve_path: "/home/ubuntu/puffer/third_party/pensieve/multi_video_sim/rl_test.py"
  #   nn_path: "/home/puffer/models/pensieve/nn_model_ep_77400.ckpt"


  # abr: mpc
  # abr_config:
  #   rebuffer_length_coeff: 100


  # abr: robust_mpc
  # abr_config:
  #   rebuffer_length_coeff: 100

  # abr: puffer_ttp
  # abr_config:
  #   model_dir: ./weights/ttp/original
  #   rebuffer_length_coeff: 100
  #   collect_data: true
  #   hidden2_model_dir: ./weights/ttp/hidden2/
  #   max_lookahead_horizon: 1


constants:
  deleted_cols: ['file_index', 'chunk_index', 'max_pacing_rate', 'reordering',
                  'advmss', 'pmtu', 'fackets', 'snd_mss', 'probes']
  to_delete_cols: ['file_index', 'max_pacing_rate', 'reordering',
                  'advmss', 'pmtu', 'fackets', 'snd_mss', 'probes']


  qualities: ['426x240', '640x360', '854x480', '1280x720', '1920x1080']
  quality_cols: ['file_index', 'chunk_index', 'ssim', 'video_buffer',
                  'cum_rebuffer', 'media_chunk_size', 'trans_time',

                  'qoe', 'ssim_quality', 'ssim_change', 'rebuffer', 
                  'bit_quality', 'bit_change']

  cc_cols: ['file_index', 'chunk_index', 'sndbuf_limited', 'rwnd_limited', 'busy_time',
            'delivery_rate', 'data_segs_out', 'data_segs_in', 'min_rtt', 'notsent_bytes',
            'segs_in', 'segs_out', 'bytes_received', 'bytes_acked', 'max_pacing_rate',
            'total_retrans', 'rcv_space', 'rcv_rtt', 'reordering', 'advmss',
            'snd_cwnd', 'snd_ssthresh', 'rttvar', 'rtt', 'rcv_ssthresh', 'pmtu',
            'last_ack_recv', 'last_data_recv', 'last_data_sent', 'fackets',
            'retrans', 'lost', 'sacked', 'unacked', 'rcv_mss', 'snd_mss', 'ato',
            'rto', 'backoff', 'probes', 'ca_state', 'timestamp']

simulation_constants:
  clients: 7 # num clients in simulation generating data and training

  # how many iterations over the trace dir
  epochs_training: 2
  epochs_generating_data: 1
  epochs_testing: 1

  trace_dir: './traces/final_traces/' # the folder that holds the final traces
  yml_output_dir: '/home/mike/puffer/src/' # the folder to contain the final settings.yml for the simulation

  delay: -1.0 # default delay for the simulation, -1.0 means not to use this value
  loss: 0.0 # default delay for the simulation, -1.0 means not to use this value

  mahimahi_epochs: 1 # how many iterations over the trace dir

  remote_base_port: 9222
  base_port: 9360

  delays: [100, 30, 40, 60]
  losses: [0, 0.02, 0.05, 0.01]


