// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http_record.proto

#ifndef PROTOBUF_http_5frecord_2eproto__INCLUDED
#define PROTOBUF_http_5frecord_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace MahimahiProtobufs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_http_5frecord_2eproto();
void protobuf_AssignDesc_http_5frecord_2eproto();
void protobuf_ShutdownFile_http_5frecord_2eproto();

class HTTPHeader;
class HTTPMessage;
class RequestResponse;

enum RequestResponse_Scheme {
  RequestResponse_Scheme_HTTP = 1,
  RequestResponse_Scheme_HTTPS = 2
};
bool RequestResponse_Scheme_IsValid(int value);
const RequestResponse_Scheme RequestResponse_Scheme_Scheme_MIN = RequestResponse_Scheme_HTTP;
const RequestResponse_Scheme RequestResponse_Scheme_Scheme_MAX = RequestResponse_Scheme_HTTPS;
const int RequestResponse_Scheme_Scheme_ARRAYSIZE = RequestResponse_Scheme_Scheme_MAX + 1;

const ::google::protobuf::EnumDescriptor* RequestResponse_Scheme_descriptor();
inline const ::std::string& RequestResponse_Scheme_Name(RequestResponse_Scheme value) {
  return ::google::protobuf::internal::NameOfEnum(
    RequestResponse_Scheme_descriptor(), value);
}
inline bool RequestResponse_Scheme_Parse(
    const ::std::string& name, RequestResponse_Scheme* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestResponse_Scheme>(
    RequestResponse_Scheme_descriptor(), name, value);
}
// ===================================================================

class HTTPMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MahimahiProtobufs.HTTPMessage) */ {
 public:
  HTTPMessage();
  virtual ~HTTPMessage();

  HTTPMessage(const HTTPMessage& from);

  inline HTTPMessage& operator=(const HTTPMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HTTPMessage& default_instance();

  void Swap(HTTPMessage* other);

  // implements Message ----------------------------------------------

  inline HTTPMessage* New() const { return New(NULL); }

  HTTPMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HTTPMessage& from);
  void MergeFrom(const HTTPMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HTTPMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes first_line = 1;
  bool has_first_line() const;
  void clear_first_line();
  static const int kFirstLineFieldNumber = 1;
  const ::std::string& first_line() const;
  void set_first_line(const ::std::string& value);
  void set_first_line(const char* value);
  void set_first_line(const void* value, size_t size);
  ::std::string* mutable_first_line();
  ::std::string* release_first_line();
  void set_allocated_first_line(::std::string* first_line);

  // repeated .MahimahiProtobufs.HTTPHeader header = 2;
  int header_size() const;
  void clear_header();
  static const int kHeaderFieldNumber = 2;
  const ::MahimahiProtobufs::HTTPHeader& header(int index) const;
  ::MahimahiProtobufs::HTTPHeader* mutable_header(int index);
  ::MahimahiProtobufs::HTTPHeader* add_header();
  ::google::protobuf::RepeatedPtrField< ::MahimahiProtobufs::HTTPHeader >*
      mutable_header();
  const ::google::protobuf::RepeatedPtrField< ::MahimahiProtobufs::HTTPHeader >&
      header() const;

  // optional bytes body = 3;
  bool has_body() const;
  void clear_body();
  static const int kBodyFieldNumber = 3;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  void set_body(const char* value);
  void set_body(const void* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // @@protoc_insertion_point(class_scope:MahimahiProtobufs.HTTPMessage)
 private:
  inline void set_has_first_line();
  inline void clear_has_first_line();
  inline void set_has_body();
  inline void clear_has_body();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr first_line_;
  ::google::protobuf::RepeatedPtrField< ::MahimahiProtobufs::HTTPHeader > header_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  friend void  protobuf_AddDesc_http_5frecord_2eproto();
  friend void protobuf_AssignDesc_http_5frecord_2eproto();
  friend void protobuf_ShutdownFile_http_5frecord_2eproto();

  void InitAsDefaultInstance();
  static HTTPMessage* default_instance_;
};
// -------------------------------------------------------------------

class HTTPHeader : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MahimahiProtobufs.HTTPHeader) */ {
 public:
  HTTPHeader();
  virtual ~HTTPHeader();

  HTTPHeader(const HTTPHeader& from);

  inline HTTPHeader& operator=(const HTTPHeader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HTTPHeader& default_instance();

  void Swap(HTTPHeader* other);

  // implements Message ----------------------------------------------

  inline HTTPHeader* New() const { return New(NULL); }

  HTTPHeader* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HTTPHeader& from);
  void MergeFrom(const HTTPHeader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HTTPHeader* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const void* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // optional bytes value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:MahimahiProtobufs.HTTPHeader)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend void  protobuf_AddDesc_http_5frecord_2eproto();
  friend void protobuf_AssignDesc_http_5frecord_2eproto();
  friend void protobuf_ShutdownFile_http_5frecord_2eproto();

  void InitAsDefaultInstance();
  static HTTPHeader* default_instance_;
};
// -------------------------------------------------------------------

class RequestResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MahimahiProtobufs.RequestResponse) */ {
 public:
  RequestResponse();
  virtual ~RequestResponse();

  RequestResponse(const RequestResponse& from);

  inline RequestResponse& operator=(const RequestResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestResponse& default_instance();

  void Swap(RequestResponse* other);

  // implements Message ----------------------------------------------

  inline RequestResponse* New() const { return New(NULL); }

  RequestResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestResponse& from);
  void MergeFrom(const RequestResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RequestResponse_Scheme Scheme;
  static const Scheme HTTP =
    RequestResponse_Scheme_HTTP;
  static const Scheme HTTPS =
    RequestResponse_Scheme_HTTPS;
  static inline bool Scheme_IsValid(int value) {
    return RequestResponse_Scheme_IsValid(value);
  }
  static const Scheme Scheme_MIN =
    RequestResponse_Scheme_Scheme_MIN;
  static const Scheme Scheme_MAX =
    RequestResponse_Scheme_Scheme_MAX;
  static const int Scheme_ARRAYSIZE =
    RequestResponse_Scheme_Scheme_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Scheme_descriptor() {
    return RequestResponse_Scheme_descriptor();
  }
  static inline const ::std::string& Scheme_Name(Scheme value) {
    return RequestResponse_Scheme_Name(value);
  }
  static inline bool Scheme_Parse(const ::std::string& name,
      Scheme* value) {
    return RequestResponse_Scheme_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string ip = 1;
  bool has_ip() const;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // optional uint32 port = 2;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // optional .MahimahiProtobufs.RequestResponse.Scheme scheme = 3;
  bool has_scheme() const;
  void clear_scheme();
  static const int kSchemeFieldNumber = 3;
  ::MahimahiProtobufs::RequestResponse_Scheme scheme() const;
  void set_scheme(::MahimahiProtobufs::RequestResponse_Scheme value);

  // optional .MahimahiProtobufs.HTTPMessage request = 4;
  bool has_request() const;
  void clear_request();
  static const int kRequestFieldNumber = 4;
  const ::MahimahiProtobufs::HTTPMessage& request() const;
  ::MahimahiProtobufs::HTTPMessage* mutable_request();
  ::MahimahiProtobufs::HTTPMessage* release_request();
  void set_allocated_request(::MahimahiProtobufs::HTTPMessage* request);

  // optional .MahimahiProtobufs.HTTPMessage response = 5;
  bool has_response() const;
  void clear_response();
  static const int kResponseFieldNumber = 5;
  const ::MahimahiProtobufs::HTTPMessage& response() const;
  ::MahimahiProtobufs::HTTPMessage* mutable_response();
  ::MahimahiProtobufs::HTTPMessage* release_response();
  void set_allocated_response(::MahimahiProtobufs::HTTPMessage* response);

  // @@protoc_insertion_point(class_scope:MahimahiProtobufs.RequestResponse)
 private:
  inline void set_has_ip();
  inline void clear_has_ip();
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_scheme();
  inline void clear_has_scheme();
  inline void set_has_request();
  inline void clear_has_request();
  inline void set_has_response();
  inline void clear_has_response();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::uint32 port_;
  int scheme_;
  ::MahimahiProtobufs::HTTPMessage* request_;
  ::MahimahiProtobufs::HTTPMessage* response_;
  friend void  protobuf_AddDesc_http_5frecord_2eproto();
  friend void protobuf_AssignDesc_http_5frecord_2eproto();
  friend void protobuf_ShutdownFile_http_5frecord_2eproto();

  void InitAsDefaultInstance();
  static RequestResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HTTPMessage

// optional bytes first_line = 1;
inline bool HTTPMessage::has_first_line() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HTTPMessage::set_has_first_line() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HTTPMessage::clear_has_first_line() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HTTPMessage::clear_first_line() {
  first_line_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_first_line();
}
inline const ::std::string& HTTPMessage::first_line() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.HTTPMessage.first_line)
  return first_line_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPMessage::set_first_line(const ::std::string& value) {
  set_has_first_line();
  first_line_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MahimahiProtobufs.HTTPMessage.first_line)
}
inline void HTTPMessage::set_first_line(const char* value) {
  set_has_first_line();
  first_line_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MahimahiProtobufs.HTTPMessage.first_line)
}
inline void HTTPMessage::set_first_line(const void* value, size_t size) {
  set_has_first_line();
  first_line_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MahimahiProtobufs.HTTPMessage.first_line)
}
inline ::std::string* HTTPMessage::mutable_first_line() {
  set_has_first_line();
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.HTTPMessage.first_line)
  return first_line_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HTTPMessage::release_first_line() {
  // @@protoc_insertion_point(field_release:MahimahiProtobufs.HTTPMessage.first_line)
  clear_has_first_line();
  return first_line_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPMessage::set_allocated_first_line(::std::string* first_line) {
  if (first_line != NULL) {
    set_has_first_line();
  } else {
    clear_has_first_line();
  }
  first_line_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), first_line);
  // @@protoc_insertion_point(field_set_allocated:MahimahiProtobufs.HTTPMessage.first_line)
}

// repeated .MahimahiProtobufs.HTTPHeader header = 2;
inline int HTTPMessage::header_size() const {
  return header_.size();
}
inline void HTTPMessage::clear_header() {
  header_.Clear();
}
inline const ::MahimahiProtobufs::HTTPHeader& HTTPMessage::header(int index) const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.HTTPMessage.header)
  return header_.Get(index);
}
inline ::MahimahiProtobufs::HTTPHeader* HTTPMessage::mutable_header(int index) {
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.HTTPMessage.header)
  return header_.Mutable(index);
}
inline ::MahimahiProtobufs::HTTPHeader* HTTPMessage::add_header() {
  // @@protoc_insertion_point(field_add:MahimahiProtobufs.HTTPMessage.header)
  return header_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MahimahiProtobufs::HTTPHeader >*
HTTPMessage::mutable_header() {
  // @@protoc_insertion_point(field_mutable_list:MahimahiProtobufs.HTTPMessage.header)
  return &header_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MahimahiProtobufs::HTTPHeader >&
HTTPMessage::header() const {
  // @@protoc_insertion_point(field_list:MahimahiProtobufs.HTTPMessage.header)
  return header_;
}

// optional bytes body = 3;
inline bool HTTPMessage::has_body() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HTTPMessage::set_has_body() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HTTPMessage::clear_has_body() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HTTPMessage::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_body();
}
inline const ::std::string& HTTPMessage::body() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.HTTPMessage.body)
  return body_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPMessage::set_body(const ::std::string& value) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MahimahiProtobufs.HTTPMessage.body)
}
inline void HTTPMessage::set_body(const char* value) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MahimahiProtobufs.HTTPMessage.body)
}
inline void HTTPMessage::set_body(const void* value, size_t size) {
  set_has_body();
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MahimahiProtobufs.HTTPMessage.body)
}
inline ::std::string* HTTPMessage::mutable_body() {
  set_has_body();
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.HTTPMessage.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HTTPMessage::release_body() {
  // @@protoc_insertion_point(field_release:MahimahiProtobufs.HTTPMessage.body)
  clear_has_body();
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPMessage::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    set_has_body();
  } else {
    clear_has_body();
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:MahimahiProtobufs.HTTPMessage.body)
}

// -------------------------------------------------------------------

// HTTPHeader

// optional bytes key = 1;
inline bool HTTPHeader::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HTTPHeader::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HTTPHeader::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HTTPHeader::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& HTTPHeader::key() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.HTTPHeader.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPHeader::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MahimahiProtobufs.HTTPHeader.key)
}
inline void HTTPHeader::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MahimahiProtobufs.HTTPHeader.key)
}
inline void HTTPHeader::set_key(const void* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MahimahiProtobufs.HTTPHeader.key)
}
inline ::std::string* HTTPHeader::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.HTTPHeader.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HTTPHeader::release_key() {
  // @@protoc_insertion_point(field_release:MahimahiProtobufs.HTTPHeader.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPHeader::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:MahimahiProtobufs.HTTPHeader.key)
}

// optional bytes value = 2;
inline bool HTTPHeader::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HTTPHeader::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HTTPHeader::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HTTPHeader::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& HTTPHeader::value() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.HTTPHeader.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPHeader::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MahimahiProtobufs.HTTPHeader.value)
}
inline void HTTPHeader::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MahimahiProtobufs.HTTPHeader.value)
}
inline void HTTPHeader::set_value(const void* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MahimahiProtobufs.HTTPHeader.value)
}
inline ::std::string* HTTPHeader::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.HTTPHeader.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HTTPHeader::release_value() {
  // @@protoc_insertion_point(field_release:MahimahiProtobufs.HTTPHeader.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HTTPHeader::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:MahimahiProtobufs.HTTPHeader.value)
}

// -------------------------------------------------------------------

// RequestResponse

// optional string ip = 1;
inline bool RequestResponse::has_ip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestResponse::set_has_ip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestResponse::clear_has_ip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestResponse::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ip();
}
inline const ::std::string& RequestResponse::ip() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.RequestResponse.ip)
  return ip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestResponse::set_ip(const ::std::string& value) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MahimahiProtobufs.RequestResponse.ip)
}
inline void RequestResponse::set_ip(const char* value) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MahimahiProtobufs.RequestResponse.ip)
}
inline void RequestResponse::set_ip(const char* value, size_t size) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MahimahiProtobufs.RequestResponse.ip)
}
inline ::std::string* RequestResponse::mutable_ip() {
  set_has_ip();
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.RequestResponse.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestResponse::release_ip() {
  // @@protoc_insertion_point(field_release:MahimahiProtobufs.RequestResponse.ip)
  clear_has_ip();
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestResponse::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    set_has_ip();
  } else {
    clear_has_ip();
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:MahimahiProtobufs.RequestResponse.ip)
}

// optional uint32 port = 2;
inline bool RequestResponse::has_port() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestResponse::set_has_port() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestResponse::clear_has_port() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestResponse::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 RequestResponse::port() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.RequestResponse.port)
  return port_;
}
inline void RequestResponse::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:MahimahiProtobufs.RequestResponse.port)
}

// optional .MahimahiProtobufs.RequestResponse.Scheme scheme = 3;
inline bool RequestResponse::has_scheme() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestResponse::set_has_scheme() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestResponse::clear_has_scheme() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestResponse::clear_scheme() {
  scheme_ = 1;
  clear_has_scheme();
}
inline ::MahimahiProtobufs::RequestResponse_Scheme RequestResponse::scheme() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.RequestResponse.scheme)
  return static_cast< ::MahimahiProtobufs::RequestResponse_Scheme >(scheme_);
}
inline void RequestResponse::set_scheme(::MahimahiProtobufs::RequestResponse_Scheme value) {
  assert(::MahimahiProtobufs::RequestResponse_Scheme_IsValid(value));
  set_has_scheme();
  scheme_ = value;
  // @@protoc_insertion_point(field_set:MahimahiProtobufs.RequestResponse.scheme)
}

// optional .MahimahiProtobufs.HTTPMessage request = 4;
inline bool RequestResponse::has_request() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RequestResponse::set_has_request() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RequestResponse::clear_has_request() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RequestResponse::clear_request() {
  if (request_ != NULL) request_->::MahimahiProtobufs::HTTPMessage::Clear();
  clear_has_request();
}
inline const ::MahimahiProtobufs::HTTPMessage& RequestResponse::request() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.RequestResponse.request)
  return request_ != NULL ? *request_ : *default_instance_->request_;
}
inline ::MahimahiProtobufs::HTTPMessage* RequestResponse::mutable_request() {
  set_has_request();
  if (request_ == NULL) {
    request_ = new ::MahimahiProtobufs::HTTPMessage;
  }
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.RequestResponse.request)
  return request_;
}
inline ::MahimahiProtobufs::HTTPMessage* RequestResponse::release_request() {
  // @@protoc_insertion_point(field_release:MahimahiProtobufs.RequestResponse.request)
  clear_has_request();
  ::MahimahiProtobufs::HTTPMessage* temp = request_;
  request_ = NULL;
  return temp;
}
inline void RequestResponse::set_allocated_request(::MahimahiProtobufs::HTTPMessage* request) {
  delete request_;
  request_ = request;
  if (request) {
    set_has_request();
  } else {
    clear_has_request();
  }
  // @@protoc_insertion_point(field_set_allocated:MahimahiProtobufs.RequestResponse.request)
}

// optional .MahimahiProtobufs.HTTPMessage response = 5;
inline bool RequestResponse::has_response() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RequestResponse::set_has_response() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RequestResponse::clear_has_response() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RequestResponse::clear_response() {
  if (response_ != NULL) response_->::MahimahiProtobufs::HTTPMessage::Clear();
  clear_has_response();
}
inline const ::MahimahiProtobufs::HTTPMessage& RequestResponse::response() const {
  // @@protoc_insertion_point(field_get:MahimahiProtobufs.RequestResponse.response)
  return response_ != NULL ? *response_ : *default_instance_->response_;
}
inline ::MahimahiProtobufs::HTTPMessage* RequestResponse::mutable_response() {
  set_has_response();
  if (response_ == NULL) {
    response_ = new ::MahimahiProtobufs::HTTPMessage;
  }
  // @@protoc_insertion_point(field_mutable:MahimahiProtobufs.RequestResponse.response)
  return response_;
}
inline ::MahimahiProtobufs::HTTPMessage* RequestResponse::release_response() {
  // @@protoc_insertion_point(field_release:MahimahiProtobufs.RequestResponse.response)
  clear_has_response();
  ::MahimahiProtobufs::HTTPMessage* temp = response_;
  response_ = NULL;
  return temp;
}
inline void RequestResponse::set_allocated_response(::MahimahiProtobufs::HTTPMessage* response) {
  delete response_;
  response_ = response;
  if (response) {
    set_has_response();
  } else {
    clear_has_response();
  }
  // @@protoc_insertion_point(field_set_allocated:MahimahiProtobufs.RequestResponse.response)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace MahimahiProtobufs

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MahimahiProtobufs::RequestResponse_Scheme> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MahimahiProtobufs::RequestResponse_Scheme>() {
  return ::MahimahiProtobufs::RequestResponse_Scheme_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_http_5frecord_2eproto__INCLUDED
